# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# the sequencing adapter
adapter: ACGGATCGATCGATCGATCGAT

species: hsapiens

reference:
  # the reference genome
  index: "/path/to/genome"
  # the salmon index
  salmon_index: "/path/to/salmon/index"
  # gtf file with transcripts
  annotation: "path/to/gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
    # contrasts for the deseq2 results method
    contrasts:
        tumor-vs-healthy:
            - tumor
            - healthy


params:
    salmon_index:
        ""
    salmon_quant:
        ""
    deseq:
        ""
